/* WINEFUNDAY_PAIRING_ICONS_V9 — engraved PNG sprite via direct image; visual-only */
(()=>{'use strict';
const POS={aperitif:[0,0],fish:[1,0],seafood:[2,0],scallop:[3,0],oyster:[4,0],poultry:[5,0],beef:[0,1],lamb:[1,1],game:[2,1],wildpoultry:[3,1],cheese:[4,1],truffle:[5,1],vegetable:[0,2],mushroom:[1,2],mediterranean:[2,2],asian:[3,2],dessert:[4,2],chocolate:[5,2]};
function typeFor(label){const t=(label||'').toLowerCase();if(/fasan|wachtel|wildgeflügel|wildgefluegel/.test(t))return'wildpoultry';if(/jakobsmuschel|scallop/.test(t))return'scallop';if(/auster|oyster/.test(t))return'oyster';if(/kaviar|caviar|meeresfrüchte|meeresfruechte|seafood|garnele|shrimp|krabbe|krebs|hummer|lobster|muschel/.test(t))return'seafood';if(/aperitif|apéritif/.test(t))return'aperitif';if(/zander|saibling|forelle|fisch|lachs|thunfisch|seezunge|steinbutt|kabeljau/.test(t))return'fish';if(/wagyu|tafelspitz|geschmort.*rind|rind|steak|rinder?filet|entrec[oô]te|roastbeef/.test(t))return'beef';if(/lamm|karree/.test(t))return'lamb';if(/wild|reh|hirsch|venison/.test(t))return'game';if(/brathendl|backhendl|hendl|huhn|hähn|haehn|geflügel|gefluegel|poularde|poulet/.test(t))return'poultry';if(/trüffel|trueffel/.test(t))return'truffle';if(/käse|kaese|parmesan|ziegenkäse|ziegenkaese|blauschimmel/.test(t))return'cheese';if(/pilz|steinpilz|morchel|champignon/.test(t))return'mushroom';if(/spargel|gemüse|gemuese|artischock|zucchini|aubergine|fenchel|tomat/.test(t))return'vegetable';if(/asiatisch|asia|sushi|curry|thai/.test(t))return'asian';if(/mediterran|pizza|pasta|risotto/.test(t))return'mediterranean';if(/schokolade|chocolate/.test(t))return'chocolate';if(/dessert|kuchen|tarte|süß|suess/.test(t))return'dessert';return null}
function apply(){document.querySelectorAll('.wf-pair').forEach(pair=>{const label=pair.querySelector('.wf-pl')?.textContent||'',type=typeFor(label),p=POS[type],box=pair.querySelector('.wf-pi');if(!type||!p||!box||box.dataset.wfPngIcon===type)return;box.innerHTML='';box.style.overflow='hidden';box.style.position='relative';const img=document.createElement('img');img.src='pairing/pairing-sprite.png?v=9';img.alt='';img.setAttribute('aria-hidden','true');img.style.cssText='position:absolute!important;width:204px!important;height:86.42px!important;max-width:none!important;left:'+(-34*p[0])+'px!important;top:'+(2.6-28.81*p[1])+'px!important;display:block!important;';box.appendChild(img);box.dataset.wfPngIcon=type})}
function schedule(){setTimeout(apply,80)}
window.WinefundayPairingIconsApply=apply;
window.addEventListener('load',schedule,{once:true});
document.addEventListener('click',schedule,false);
})();
