/* WINEFUNDAY_PAIRING_ICONS_V8 — engraved PNG sprite; visual-only, Insights logic untouched */
(()=>{'use strict';
const POS={aperitif:[0,0],fish:[1,0],seafood:[2,0],scallop:[3,0],oyster:[4,0],poultry:[5,0],beef:[0,1],lamb:[1,1],game:[2,1],wildpoultry:[3,1],cheese:[4,1],truffle:[5,1],vegetable:[0,2],mushroom:[1,2],mediterranean:[2,2],asian:[3,2],dessert:[4,2],chocolate:[5,2]};
function typeFor(label){const t=(label||'').toLowerCase();if(/fasan|wachtel|wildgeflügel|wildgefluegel/.test(t))return'wildpoultry';if(/jakobsmuschel|scallop/.test(t))return'scallop';if(/auster|oyster/.test(t))return'oyster';if(/meeresfrüchte|meeresfruechte|seafood|garnele|shrimp|krabbe|krebs|hummer|lobster|muschel/.test(t))return'seafood';if(/aperitif|apéritif/.test(t))return'aperitif';if(/zander|saibling|forelle|fisch|lachs|thunfisch|seezunge|steinbutt|kabeljau/.test(t))return'fish';if(/tafelspitz|geschmort.*rind|rind|steak|rinder?filet|entrec[oô]te|roastbeef/.test(t))return'beef';if(/lamm|karree/.test(t))return'lamb';if(/wild|reh|hirsch|venison/.test(t))return'game';if(/brathendl|backhendl|hendl|huhn|hähn|haehn|geflügel|gefluegel|poularde|poulet/.test(t))return'poultry';if(/trüffel|trueffel/.test(t))return'truffle';if(/käse|kaese|parmesan|ziegenkäse|ziegenkaese|blauschimmel/.test(t))return'cheese';if(/pilz|steinpilz|morchel|champignon/.test(t))return'mushroom';if(/spargel|gemüse|gemuese|artischock|zucchini|aubergine|fenchel|tomat/.test(t))return'vegetable';if(/asiatisch|asia|sushi|curry|thai/.test(t))return'asian';if(/mediterran|pizza|pasta|risotto/.test(t))return'mediterranean';if(/schokolade|chocolate/.test(t))return'chocolate';if(/dessert|kuchen|tarte|süß|suess/.test(t))return'dessert';return null}
function addStyle(){if(document.getElementById('wf-pairing-png-style'))return;const s=document.createElement('style');s.id='wf-pairing-png-style';s.textContent='.wf-pairing .wf-pi .wf-png-icon{display:block!important;width:34px!important;height:34px!important;background-image:url("pairing/pairing-sprite.png?v=8");background-repeat:no-repeat;background-size:204px 86.42px;transform:none!important}';document.head.appendChild(s)}
function apply(){addStyle();document.querySelectorAll('.wf-pair').forEach(pair=>{const label=pair.querySelector('.wf-pl')?.textContent||'';const type=typeFor(label),p=POS[type],box=pair.querySelector('.wf-pi');if(!type||!p||!box||box.dataset.wfPngIcon===type)return;const x=-34*p[0],y=2.6-28.81*p[1];box.innerHTML='<span class="wf-png-icon" aria-hidden="true"></span>';const icon=box.firstElementChild;icon.style.backgroundPosition=x+'px '+y+'px';box.dataset.wfPngIcon=type})}
function schedule(){setTimeout(apply,80)}
window.WinefundayPairingIconsApply=apply;
window.addEventListener('load',schedule,{once:true});
document.addEventListener('click',schedule,false);
})();
