(()=>{
 const id=new URLSearchParams(location.search).get('id');if(!id||location.pathname.startsWith('/weinkeller/'))return;
 const style=document.createElement('style');style.textContent=`.wf-moment{background:#e3e8e5;border:1px solid #c8d2ce;border-radius:16px;padding:24px;margin:24px 0;color:#004438}.wf-moment h3{font:28px Georgia,serif;margin:0 0 12px}.wf-moment p{line-height:1.5}.wf-moment-actions{display:flex;flex-wrap:wrap;gap:10px}.wf-moment a,.wf-moment button,.wf-share button,.wf-share a{font:inherit;display:inline-block;border:1px solid #004438;border-radius:24px;padding:12px 18px;text-decoration:none;background:#004438;color:white;cursor:pointer}.wf-moment button{background:transparent;color:#004438}.wf-share{width:min(430px,calc(100% - 40px));max-height:85dvh;overflow:auto;background:#f9f6f3;color:#004438;border:0;border-radius:16px;padding:24px}.wf-share::backdrop{background:#0008}.wf-share h3{font:28px Georgia,serif}.wf-share img{display:block;max-width:100%;max-height:35dvh;margin:16px auto}.wf-share .close{float:right;background:transparent;color:#004438;padding:5px 12px}.wf-share button[disabled]{opacity:.5}.wf-share p{line-height:1.5}.wf-share-actions{display:flex;gap:10px;flex-wrap:wrap}.rating-box.wf-rating-target{scroll-margin-top:25px}.rating-box.wf-rating-target:focus{outline:2px solid #004438;outline-offset:6px}@media(max-width:500px){.wf-moment{padding:18px}.wf-moment-actions>*{flex:1;text-align:center}}`;document.head.append(style);
 function mount(){const rating=document.querySelector('.rating-box');if(!rating||document.querySelector('.wf-moment'))return false;
 rating.classList.add('wf-rating-target');rating.id='wein-bewerten';rating.tabIndex=-1;
 const section=document.createElement('section');section.className='wf-moment';section.innerHTML=`<h3>Wie schmeckt Ihr Weinmoment?</h3><p>Bewerten Sie Ihren Wein mit ein bis fünf Sternen. Entdecken Sie weitere Weinmomente im Winefunday Social Club – oder teilen Sie ein Foto von sich und Ihrer Flasche bei uns im Restaurant.</p><div class="wf-moment-actions"><button type="button" data-rate>Wein bewerten ★</button><a href="https://www.instagram.com/winefundaysocialclub/" target="_blank" rel="noopener noreferrer">Auf Instagram folgen</a><button type="button" data-share>Weinmoment teilen</button></div><p style="font-size:14px;margin-bottom:0">Markieren Sie uns mit <strong>@winefundaysocialclub</strong>.</p>`;rating.before(section);
 section.querySelector('[data-rate]').onclick=()=>{rating.scrollIntoView({behavior:'smooth',block:'center'});rating.focus({preventScroll:true});};
 const dialog=document.createElement('dialog');dialog.className='wf-share';dialog.setAttribute('aria-label','Weinmoment teilen');dialog.innerHTML=`<button type="button" class="close" aria-label="Schließen">×</button><h3>Ihr Weinmoment</h3><p>Machen Sie ein Foto von sich und Ihrer Flasche im Restaurant oder wählen Sie ein vorhandenes Bild aus.</p><input type="file" accept="image/*" hidden><img alt="Ihr ausgewähltes Foto" hidden><div class="wf-share-actions"><button type="button" data-photo>Foto aufnehmen / auswählen</button><button type="button" data-send disabled>Foto teilen</button></div><p>Markieren Sie <strong>@winefundaysocialclub</strong> auf Instagram. Das Folgen und Veröffentlichen bestätigen Sie selbst.</p><p style="font-size:13px">Das Foto bleibt auf Ihrem Gerät und wird nicht an Winefunday hochgeladen.</p><p data-message role="status"></p><a href="https://www.instagram.com/winefundaysocialclub/" target="_blank" rel="noopener noreferrer">Instagram öffnen</a>`;document.body.append(dialog);
 const input=dialog.querySelector('input'),preview=dialog.querySelector('img'),send=dialog.querySelector('[data-send]'),message=dialog.querySelector('[data-message]');let file,url;
 section.querySelector('[data-share]').onclick=()=>dialog.showModal();dialog.querySelector('.close').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{if(url)URL.revokeObjectURL(url);url=null;file=null;input.value='';preview.hidden=true;preview.removeAttribute('src');send.disabled=true;message.textContent='';});
 dialog.querySelector('[data-photo]').onclick=()=>input.click();input.onchange=()=>{file=input.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){message.textContent='Bitte ein Bild auswählen.';file=null;send.disabled=true;return;}if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(file);preview.src=url;preview.hidden=false;send.disabled=false;message.textContent='';};
 send.onclick=async()=>{if(!file)return;const data={files:[file],title:'Mein Weinmoment bei Gut Kaltenbrunn',text:'Mein Weinmoment bei Gut Kaltenbrunn 🍷 @winefundaysocialclub'};if(!navigator.canShare?.({files:[file]})||!navigator.share){message.textContent='Dieser Browser kann das Foto nicht direkt teilen. Öffnen Sie Instagram und wählen Sie dort Ihr Foto aus.';return;}try{await navigator.share(data);message.textContent='Wählen Sie Instagram, falls es im Teilen-Menü angeboten wird. Das Posting bestätigen Sie dort selbst.';}catch(e){if(e.name!=='AbortError')message.textContent='Teilen nicht möglich. Bitte das Foto direkt in Instagram auswählen.';}};
 return true;}
 if(!mount()){const observer=new MutationObserver(()=>{if(mount())observer.disconnect();});observer.observe(document.getElementById('app')||document.body,{childList:true,subtree:true});}
})();
